# -*- coding: utf-8 -*-
"""minutesgenerator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSJrF6Bk27oS1ZL2wCjHmAb7shwnW9D-
"""

import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")
meeting_title=input("enter meeting title: ")
date=input("enter meeting date (DD-MM-YYYY): ")
time=input("enter meeting time: ")
participants=input("enter participants (comma separated): ")
agenda=input("enter agenda points(comma separated): ")
decisions=input("enter decisions taken (comma separated): ")
action_items=input("enter action items (comma separated): ")
prepared_by=input("prepared by: ")
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
actions_list=[a.strip() for a in action_items.split(",") if a.strip()]
minutes={
    "Meeting Title": meeting_title,
    "Date":date,
    "Time":time,
    "Participants":";".join(participants_list),
    "Agenda":";".join(agenda_list),
    "Decisions Taken":",".join(decisions_list),
    "Action Items":",".join(actions_list),
    "Prepared By":prepared_by,
    "Geneated On":datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}
df=pd.DataFrame(list(minutes.items()), columns=["Field","Details"])
print("\n Metting Minutes Generated Successfully\n")
display(df)
df.to_csv("meeting_minutes.csv",index=False)
print("\n File saved as meeting_minutes.csv")