# -*- coding: utf-8 -*-
"""similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DA8RLFpzFk0okxYKJsUtCr4_TYnc6AZj
"""

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer,util

model=SentenceTransformer('all-MINILM-L6-V2')
text1=input("enter text1: ")
text2=input("enter text2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\nsimliarity score:",round(float(similarity),2))
if similarity>0.75:
  print("simliarity is high")
elif similarity>0.4:
  print("similarity is medium")
else:
  print("similarity is low")