# -*- coding: utf-8 -*-
"""Text generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bi4p9_R8LF-Tk9gYvZ5fGiommnooOnq3
"""

!pip install transformers torch

from transformers import pipeline
#loading AI model
generator= pipeline(
  "text-generation",
  model="gpt2"
)
#input prompt
prompt="Artificial Intelligence in finance will"
#generating output
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI-text")
print(result[0]['generated_text'])